### ISSUE TITLE
Can create an empty question

### ISSUE THREAD

**Issue by strburst** [JDTeamAcetabulum/qna#118]
## Explanation

I was hoping to see what the error looked like when leaving some fields blank, but apparently it's ok to leave the question text and correct answer blank too.

![emptyquestion](https://cloud.githubusercontent.com/assets/5883232/24045070/326775c2-0af4-11e7-8c23-8f2d59643cdc.png)

## Steps to reproduce

1. As an instructor, go to the form to create a new question.
1. Submit the form without entering anything.

## Severity

Minor.

**Comment by fvosburgh** [comment]
#127
