### ISSUE TITLE
As an instructor, I want to create, edit, and ask short answer questions so that I can get a greater variety feedback from students

### ISSUE THREAD

**Issue by strburst** [JDTeamAcetabulum/qna#23]
## Story/task details

As an instructor, I want to create, edit, and ask short answer questions so that I can get a greater variety of feedback from students.

Can create questions with an exact, case-insensitive answer, or questions with no correct answer.

### Given 
Instructor is logged in.

### When 
Instructor interacts with new question flow and chooses to create a short-answer question.

### Then 
Instructor should be able to create and save a short-answer question.

## Definition of done 
Short answer questions can be asked to students.

**Comment by rmkeezer** [comment]
This was completed by Bik's pull request #78
