### ISSUE TITLE
As a student, I want to see how many people in the class got a question wrong so that I can compare how well I am doing compared to my peers

### ISSUE THREAD

**Issue by strburst** [JDTeamAcetabulum/qna#26]
## Story/task details

After a question closes, some sort of bar chart/pie chart/visualization should pop up showing the basic breakdown of the percentage of students that got the question right.

### Given 
Student is logged in. A question was asked.

### When 
The question closes and the instructor hasn't disabled showing statistics afterwards.

### Then 
Show the visualization.

## Definition of done 
Visualization appears correctly and is working (i.e. basic manual test works).

**Comment by rmkeezer** [comment]
#94 solves this
