### ISSUE TITLE
Agenda for meeting 2017-01-13

### ISSUE THREAD

**Issue by strburst** [JDTeamAcetabulum/qna#4]
## Agenda

Feel free to edit this post to add new items to this list.

- Choose a name for the product (or just accept "Q and A Learning")
- High level architecture discussion
  - Choose a backend programming language
  - Choose a database
- Brainstorm and assign initial tasks for project setup
- Discuss policies for commit messages, issues, pull requests, code review, etc.
- Review User stories and choose which ones to implement first
- Go over course materials

## Architecture brainstorm

Feel free to edit this part too!

| Language | Framework | Used by |
|---|---|---
| Ruby | Ruby on Rails | Forester |
| Python | Flask | Allen, Matthew |
| Python | Django |   |
| Javascript | Node.js | Allen, Matthew |

*Python in general has probably been used by everyone.*

### Ruby on Rails

Opinionated, batteries-included MVC framework.

#### Pros
- Lots of important libraries bundled with Ruby.
- Convention-by-configuration (lots of setup done by default).

### Flask

Web server microframework.

#### Pros
- Unopinionated; very few restrictions on choice of libraries and fewer moving parts.

### Django

Batteries-included MVC framework.

#### Pros
- Lots of important libraries bundled with Django.

### Node.js

V8 Javascript engine on the server.

#### Pros
- Extensive tooling and choice of packages (through npm) and frameworks.
  - http://todomvc.com/
- Nonblocking/asynchronous model of concurrency can make things very fast.
- One language on both the frontend and backend.
  - Less context switching.
  - Frameworks usually have great integration between frontend/backend.

#### Cons
- Javascript as a language has many "gotchas".
  - Usually mitigated with language development in ES6, strict mode, and a good linter.
- Asynchronous code is more difficult to reason about; you are forced to think about concurrency.
  - Usually mitigated with promises.

## Todo afterwards
- Spike to explore backend programming languages

**Comment by fvosburgh** [comment]
I think the most important things we need to cover are deciding how our architecture will look from a very high level and focusing on having a concrete plan and set of practices going forward. We should review the team contract as well
