### ISSUE TITLE
Create initial website layout

### ISSUE THREAD

**Issue by strburst** [JDTeamAcetabulum/qna#41]
@fvosburgh says:
> we should also have a ticket for the overall theme of the app. As we will have a consistent menu bar and header per our prototype

Basically, we need to replicate the basic UI in the prototype. This should be easier now that the frontend build is in place.

Prototype: https://jdteamacetabulum.github.io/Active-Learning/index.html

**Comment by rmkeezer** [comment]
The code added to application controller in #48 can be used as starting point
