### ISSUE TITLE
Create readme with installation instructions and environment information

### ISSUE THREAD

**Issue by fvosburgh** [JDTeamAcetabulum/qna#61]
This isn't pertinent, so making this issue as a placeholder.

We need to write down a somewhat detailed guide for installing and running the application. This should include information such as any environment variables that need to be set, versions of `psql`, `rails`, `ruby`,  and `gulp`(?). We should also detail the process of installing it from the ground up.

**Comment by strburst** [comment]
The `gulp` version is listed in `package.json`, so `npm` should install the right version automatically. I think node.js and npm are pretty good with backwards compatibility, but I'm on node `v7.5.0` and npm `4.1.2`.

**Comment by strburst** [comment]
Closed by #89.
