### ISSUE TITLE
As a user, I want the product to have a consistent brand so that I can easily identify it

### ISSUE THREAD

**Issue by strburst** [JDTeamAcetabulum/qna#8]
## Story/task details

I @strburst can get started on the logo/color scheme after we pick a name if no one feels strongly.

- [x] Choose a name for the product (`qna`)
- [ ] Create a logo (an `svg`?)
- [ ] Choose a decent color scheme

### Given 
Nothing needs to happen beforehand.

### When 
Visiting the site should trigger this feature, since color, name, and logo should all be clearly visible.

### Then 
We will follow consistent design guidelines when implementing the product.

## Definition of done 
This feature is ready when the product has all the essential branding elements chosen.

**Comment by strburst** [comment]
Possible logos:
![qalogo1](https://cloud.githubusercontent.com/assets/5883232/22167360/dcddce8a-df33-11e6-87de-e4d1c2c96a76.png)
![qalogo2](https://cloud.githubusercontent.com/assets/5883232/22167361/df3c1ef2-df33-11e6-8f28-01758f6e982f.png)

**Comment by fvosburgh** [comment]
@strburst the branding idea is pretty cool. I like the logos so far as well. However, will this ticket also apply to the overall theme of the app itself? Or is this just for colorscheme and logo as a precursor to that?

**Comment by fvosburgh** [comment]
@strburst we should also have a ticket for the overall theme of the app. As we will have a consistent menu bar and header per our prototype

**Comment by strburst** [comment]
Closing because there hasn't been much discussion, and the choice of colors/logo/etc. is arguably best decided over a group chat/in person.
