### ISSUE TITLE
Recalibrate iteration plan

### ISSUE THREAD

**Issue by strburst** [JDTeamAcetabulum/qna#84]
You can see from Zenhub's velocity tracker

![velocity](https://cloud.githubusercontent.com/assets/5883232/23146502/646490b2-f7a5-11e6-950c-d0743cfd182f.png)

that we have been getting stuff done, but there's been a bit of a build-up on Sprint 3. We should try to balance out the story points to Sprint 4 and Sprint 5 (still leaving a bit of slack on Sprint 5 though, since it's the last sprint). Now is a good time since we need to update our iteration plan anyway.

**Comment by strburst** [comment]
Iteration plan was recalibrated.

![velocity2](https://cloud.githubusercontent.com/assets/5883232/23315370/f37a6286-fa93-11e6-9006-caf9fd21264c.png)

Now we just need to update the document.

**Comment by fvosburgh** [comment]
@strburst the document has been updated. It is worth noting that sprint 4 does have a large amount of work assigned to it. Closing this issue.
