### ISSUE TITLE
Datatables won't load until page refresh

### ISSUE THREAD

**Issue by hurtfulthings** [JDTeamAcetabulum/qna#93]
## Explanation
- Questions page has to be refreshed in order for datatables to load, likely due to conflict between jQuery and Turbolinks

## Steps to reproduce
- Go to questions page. Table will not display correctly until page is refreshed.

**Comment by strburst** [comment]
I believe we can simply disable Turbolinks if it is causing problems. From what I've read, it's [included by default in Rails 5](https://www.sitepoint.com/whats-new-rails-5/) and makes pages load faster, similar to a single-page app, but perhaps for our purposes, we don't need the speed improvement. @fvosburgh do you think we should keep Turbolinks?

@hurtfulthings Did you realize Turbolinks was the culprit by disabling it and seeing what happened? If you haven't tried that I would recommend it. (I think maybe you can do that by commenting out https://github.com/JDTeamAcetabulum/qna/blob/master/app/views/layouts/application.html.haml#L8.)
